cinema/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('movies.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

movies/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.main_page, name='main_page'),
    url(r'^add_film/$', views.add_film, name='add_film'),
    url(r'^(?P<genre>[-\w.]+)/$', views.genre_page, name='genre_page'),
    url(r'^detail/(?P<slug>[-\w.]+)/$', views.movie_detail, name='detail'),
]

movies/models.py
from django.db import models
from sorl.thumbnail import ImageField
from django.core.urlresolvers import reverse
from django.template.defaultfilters import slugify
from unidecode import unidecode


class Movie(models.Model):
    GENRE_CHOICES = (
        ('comedy', 'Comedy'),
        ('action', 'Action'),
        ('adventure', 'Adventure'),
        ('crime', 'Crime'),
        ('drama', 'Drama'),
    )

    title = models.CharField(max_length=100, unique=True)
    image = ImageField(upload_to='movies/%Y/%m/%d')
    description = models.TextField()
    slug = models.SlugField(help_text="A short label, generally used in URLs.", unique=True)
    genre = models.CharField(choices=GENRE_CHOICES, max_length=40)
    duration = models.PositiveSmallIntegerField(help_text="Film duration, in minutes.")
    price = models.PositiveSmallIntegerField(help_text="Price of one ticket, in dollars.")
    start_time = models.DateTimeField(help_text="When film will be show in cinema.")
    release_date = models.DateField(help_text="When film was releaded.")

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('detail', args=[self.slug])

    def save(self, *args, **kwargs):
        self.slug = slugify(unidecode(self.title))
        super(Movie, self).save(*args, **kwargs)

class Places(models.Model):
    chain_models = models.OneToOneField(Movie, on_delete=models.CASCADE)

    row1_place1 = models.BooleanField(default=False)
    row1_place2 = models.BooleanField(default=False)
    row1_place3 = models.BooleanField(default=False)
    row1_place4 = models.BooleanField(default=False)
    row1_place5 = models.BooleanField(default=False)
    row1_place6 = models.BooleanField(default=False)
    row1_place7 = models.BooleanField(default=False)
    row1_place8 = models.BooleanField(default=False)

    row2_place1 = models.BooleanField(default=False)
    row2_place2 = models.BooleanField(default=False)
    row2_place3 = models.BooleanField(default=False)
    row2_place4 = models.BooleanField(default=False)
    row2_place5 = models.BooleanField(default=False)
    row2_place6 = models.BooleanField(default=False)
    row2_place7 = models.BooleanField(default=False)
    row2_place8 = models.BooleanField(default=False)

    row3_place1 = models.BooleanField(default=False)
    row3_place2 = models.BooleanField(default=False)
    row3_place3 = models.BooleanField(default=False)
    row3_place4 = models.BooleanField(default=False)
    row3_place5 = models.BooleanField(default=False)
    row3_place6 = models.BooleanField(default=False)
    row3_place7 = models.BooleanField(default=False)
    row3_place8 = models.BooleanField(default=False)

    row4_place1 = models.BooleanField(default=False)
    row4_place2 = models.BooleanField(default=False)
    row4_place3 = models.BooleanField(default=False)
    row4_place4 = models.BooleanField(default=False)
    row4_place5 = models.BooleanField(default=False)
    row4_place6 = models.BooleanField(default=False)
    row4_place7 = models.BooleanField(default=False)
    row4_place8 = models.BooleanField(default=False)

    row5_place1 = models.BooleanField(default=False)
    row5_place2 = models.BooleanField(default=False)
    row5_place3 = models.BooleanField(default=False)
    row5_place4 = models.BooleanField(default=False)
    row5_place5 = models.BooleanField(default=False)
    row5_place6 = models.BooleanField(default=False)
    row5_place7 = models.BooleanField(default=False)
    row5_place8 = models.BooleanField(default=False)

    def __str__(self):
        return 'Places for ' + self.chain_models.title

movies/forms.py
from django import forms
from django.template.defaultfilters import slugify
from .models import Movie, Places
from sorl.thumbnail import ImageField
import time


class AddFilmForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = ('title', 'description', 'image', 'genre', 'duration', 'price', 'start_time', 'release_date')


    def __init__(self, *args, **kwargs):
        super(AddFilmForm, self).__init__(*args, **kwargs)
        self.fields['image'].widget.attrs['class'] = 'dropzone'
        self.fields['start_time'].widget.attrs['class'] = 'start_time'
        self.fields['start_time'].widget.attrs['placeholder'] = 'YYYY-MM-DD 00:00:00'
        self.fields['release_date'].widget.attrs['class'] = 'release_date'
        self.fields['release_date'].widget.attrs['placeholder'] = 'YYYY-MM-DD'

class SearchFilmForm(forms.Form):
    search_text = forms.CharField(max_length=60)

class Placeform(forms.ModelForm):

    class Meta:
        model = Places
        fields = ('row1_place1','row1_place2','row1_place3','row1_place4','row1_place5','row1_place6','row1_place7','row1_place8',
                  'row2_place1','row2_place2','row2_place3','row2_place4','row2_place5','row2_place6','row2_place7','row2_place8',
                  'row3_place1','row3_place2','row3_place3','row3_place4','row3_place5','row3_place6','row3_place7','row3_place8',
                  'row4_place1','row4_place2','row4_place3','row4_place4','row4_place5','row4_place6','row4_place7','row4_place8',
                  'row5_place1','row5_place2','row5_place3','row5_place4','row5_place5','row5_place6','row5_place7','row5_place8')

movies/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from .forms import AddFilmForm, SearchFilmForm, Placeform
from django.urls import reverse
from .models import Movie, Places

def main_page(request, search=''):
    all_movies = Movie.objects.all()

    if request.method == 'GET':
        search_text = request.GET.get('q')
        if search_text is not None:
            all_movies = Movie.objects.filter(title__contains=search_text)

    return render(request, 'main_page.html', {'movies': all_movies})


def genre_page(request, genre):
    all_movies = Movie.objects.filter(genre=genre)
    return render(request, 'main_page.html', {'movies': all_movies })

@login_required
def add_film(request):
    if request.method == 'POST':
        form = AddFilmForm(data=request.POST,
                           files=request.FILES)
        if form.is_valid():
            this_movie = form.save()
            Places.objects.create(chain_models=this_movie)

            redirect(reverse('main_page'))
    else:
        form = AddFilmForm(instance=request.user)
    return render(request, 'add_film.html', {'film_form': form})

def movie_detail(request, slug):
    movie = get_object_or_404(Movie, slug=slug)
    places = get_object_or_404(Places, chain_models=movie)
    if request.method == 'POST':
        select_places_form = Placeform(data=request.POST, instance=places)
        if select_places_form.is_valid():
            select_places_form.save()
    else:
        select_places_form = Placeform()
    return render(request, 'detail.html', {'movie': movie, 'places': places, 'select_places_form': select_places_form})

movies/templates/add_film.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}Add new film{% endblock %}

{% block content %}
    <div class="add_film_form">
        <form action="." method="post" enctype="multipart/form-data">
            {{ film_form.as_p }}
            {% csrf_token %}
            <input type="submit" value="Add film" id='submit'>
        </form>
    </div>
{% endblock %}


{% block js %}
    Dropzone.options.myDropzone = {

        // Prevents Dropzone from uploading dropped files immediately
        autoProcessQueue : false,

        init : function() {
            var submitButton = document.querySelector("#submit")
            myDropzone = this;

            submitButton.addEventListener("click", function() {
                myDropzone.processQueue();
                // Tell Dropzone to process all queued files.
            });

        }
    }
    $('.start_time').mask('9999-99-99 99:99:99');
    $('.release_date').mask('9999-99-99');

{% endblock %}

movies/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>{% block title %}{% endblock %}</title>

        <link rel="stylesheet" href="{% static 'css/main.css' %}">
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tachyons/4.8.1/tachyons.min.css">
        <link href="{% static 'css/dropzone.min.css' %}" type="text/css" rel="stylesheet"/>


    </head>
    <body>
        <nav class="fl w-100 bg-blue washed-red">
            <div class="fl w-40 pa3 ml4 dib avenir">
                <a href="{% url 'main_page' %}" class="ph2 navbar home link b black hover-near-white">All</a>
                <a href="{% url 'genre_page' 'comedy' %}" class="ph2 navbar home link b black hover-near-white">Comedy</a>
                <a href="{% url 'genre_page' 'action' %}" class="ph2 navbar action link b black hover-near-white">Action</a>
                <a href="{% url 'genre_page' 'adventure' %}" class="ph2 navbar adventure link b black hover-near-white">Adventure</a>
                <a href="{% url 'genre_page' 'crime' %}" class="ph2 navbar crime link b black hover-near-white">Crime</a>
                <a href="{% url 'genre_page' 'drama' %}" class="ph2 navbar drama link b black hover-near-white">Drama</a>
            </div>

            <form action="{% url "main_page" %}" method="get" class="fr w-30 br3 pa2 mr4">
                 <input id="search" name="q" type="text" placeholder="Поиск">
                {% csrf_token %}
                <button type="submit" name="button">Search!</button>
            </form>


        </nav>

        <article class="tc fl w-100">
            {% block content %}


            {% endblock %}
        </article>

        <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
        <script src="{% static 'js/dropzone.min.js' %}"></script>
        <script src="{% static 'js/jquery.mask.min.js' %}"></script>
        <script type="text/javascript">
            {% block js %}

            {% endblock %}
        </script>

    </body>
</html>

movies/templates/detail.html
{% extends "base.html" %}
{% load thumbnail %}

{% block title %}
    {{ movie.title }}
{% endblock %}

{% block content %}
    <div>
        {% thumbnail movie.image "400x500" crop='100%' as im %}
            <img class='fl pa4' src="{{ im.url }}">
        {% endthumbnail %}
    </div>

    <div class="description">
        <h3 class='db tl w-60 ml7'>{{ movie.title }}</h3>
        <p class='db tl w-60 ml7'><b>Description:</b> {{ movie.description }}</p>
        <p class='db tl w-60 ml7'><b>Genre:</b> {{ movie.genre }}</p>
        <p class='db tl w-60 ml7'><b>Start time:</b> {{ movie.start_time }}</p>
        <p class='db tl w-60 ml7'><b>Duration(in minutes):</b> {{ movie.duration }}</p>
        <p class='db tl w-60 ml7'><b>Release date:</b> {{ movie.releaseDate }}</p>
        <p class='db tl w-60 ml7'><b>Price for ticket:</b> ${{ movie.price|floatformat:2 }}</p>
    </div>


    <div class="buy_tickets fl w-100">
        <h2>Buy tickets:</h2>
        <form action="." method="post">
            <div>
                Row 1:
                {{ select_places_form.row1_place1 }}
                {{ select_places_form.row1_place2 }}
                {{ select_places_form.row1_place3 }}
                {{ select_places_form.row1_place4 }}
                {{ select_places_form.row1_place5 }}
                {{ select_places_form.row1_place6 }}
                {{ select_places_form.row1_place7 }}
                {{ select_places_form.row1_place8 }}
            </div>

            <div>
                Row 2:
                {{ select_places_form.row2_place1 }}
                {{ select_places_form.row2_place2 }}
                {{ select_places_form.row2_place3 }}
                {{ select_places_form.row2_place4 }}
                {{ select_places_form.row2_place5 }}
                {{ select_places_form.row2_place6 }}
                {{ select_places_form.row2_place7 }}
                {{ select_places_form.row2_place8 }}
            </div>

            <div>
                Row 3:
                {{ select_places_form.row3_place1 }}
                {{ select_places_form.row3_place2 }}
                {{ select_places_form.row3_place3 }}
                {{ select_places_form.row3_place4 }}
                {{ select_places_form.row3_place5 }}
                {{ select_places_form.row3_place6 }}
                {{ select_places_form.row3_place7 }}
                {{ select_places_form.row3_place8 }}
            </div>

            <div>
                Row 4:
                {{ select_places_form.row4_place1 }}
                {{ select_places_form.row4_place2 }}
                {{ select_places_form.row4_place3 }}
                {{ select_places_form.row4_place4 }}
                {{ select_places_form.row4_place5 }}
                {{ select_places_form.row4_place6 }}
                {{ select_places_form.row4_place7 }}
                {{ select_places_form.row4_place8 }}
            </div>

            <div>
                Row 5:
                {{ select_places_form.row5_place1 }}
                {{ select_places_form.row5_place2 }}
                {{ select_places_form.row5_place3 }}
                {{ select_places_form.row5_place4 }}
                {{ select_places_form.row5_place5 }}
                {{ select_places_form.row5_place6 }}
                {{ select_places_form.row5_place7 }}
                {{ select_places_form.row5_place8 }}
            </div>
            {% csrf_token %}
            <input type="submit" value="Buy!">
        </form>




    </div>
{% endblock %}

{% block js %}
    {% if places.row1_place1 == True %}
        $('#id_row1_place1').attr('checked', true);
    {% endif %}
    {% if places.row1_place2 == True %}
        $('#id_row1_place2').attr('checked', true);
    {% endif %}
    {% if places.row1_place3 == True %}
        $('#id_row1_place3').attr('checked', true);
    {% endif %}
    {% if places.row1_place4 == True %}
        $('#id_row1_place4').attr('checked', true);
    {% endif %}
    {% if places.row1_place5 == True %}
        $('#id_row1_place5').attr('checked', true);
    {% endif %}
    {% if places.row1_place6 == True %}
        $('#id_row1_place6').attr('checked', true);
    {% endif %}
    {% if places.row1_place7 == True %}
        $('#id_row1_place7').attr('checked', true);
    {% endif %}
    {% if places.row1_place8 == True %}
        $('#id_row1_place8').attr('checked', true);
    {% endif %}


    {% if places.row2_place1 == True %}
        $('#id_row2_place1').attr('checked', true);
    {% endif %}
    {% if places.row2_place2 == True %}
        $('#id_row2_place2').attr('checked', true);
    {% endif %}
    {% if places.row2_place3 == True %}
        $('#id_row2_place3').attr('checked', true);
    {% endif %}
    {% if places.row2_place4 == True %}
        $('#id_row2_place4').attr('checked', true);
    {% endif %}
    {% if places.row2_place5 == True %}
        $('#id_row2_place5').attr('checked', true);
    {% endif %}
    {% if places.row2_place6 == True %}
        $('#id_row2_place6').attr('checked', true);
    {% endif %}
    {% if places.row2_place7 == True %}
        $('#id_row2_place7').attr('checked', true);
    {% endif %}
    {% if places.row2_place8 == True %}
        $('#id_row2_place8').attr('checked', true);
    {% endif %}



    {% if places.row3_place1 == True %}
        $('#id_row3_place1').attr('checked', true);
    {% endif %}
    {% if places.row3_place2 == True %}
        $('#id_row3_place2').attr('checked', true);
    {% endif %}
    {% if places.row3_place3 == True %}
        $('#id_row3_place3').attr('checked', true);
    {% endif %}
    {% if places.row3_place4 == True %}
        $('#id_row3_place4').attr('checked', true);
    {% endif %}
    {% if places.row3_place5 == True %}
        $('#id_row3_place5').attr('checked', true);
    {% endif %}
    {% if places.row3_place6 == True %}
        $('#id_row3_place6').attr('checked', true);
    {% endif %}
    {% if places.row3_place7 == True %}
        $('#id_row3_place7').attr('checked', true);
    {% endif %}
    {% if places.row3_place8 == True %}
        $('#id_row3_place8').attr('checked', true);
    {% endif %}


    {% if places.row4_place1 == True %}
        $('#id_row4_place1').attr('checked', true);
    {% endif %}
    {% if places.row4_place2 == True %}
        $('#id_row4_place2').attr('checked', true);
    {% endif %}
    {% if places.row4_place3 == True %}
        $('#id_row4_place3').attr('checked', true);
    {% endif %}
    {% if places.row4_place4 == True %}
        $('#id_row4_place4').attr('checked', true);
    {% endif %}
    {% if places.row4_place5 == True %}
        $('#id_row4_place5').attr('checked', true);
    {% endif %}
    {% if places.row4_place6 == True %}
        $('#id_row4_place6').attr('checked', true);
    {% endif %}
    {% if places.row4_place7 == True %}
        $('#id_row4_place7').attr('checked', true);
    {% endif %}
    {% if places.row4_place8 == True %}
        $('#id_row4_place8').attr('checked', true);
    {% endif %}



    {% if places.row5_place1 == True %}
        $('#id_row5_place1').attr('checked', true);
    {% endif %}
    {% if places.row5_place2 == True %}
        $('#id_row5_place2').attr('checked', true);
    {% endif %}
    {% if places.row5_place3 == True %}
        $('#id_row5_place3').attr('checked', true);
    {% endif %}
    {% if places.row5_place4 == True %}
        $('#id_row5_place4').attr('checked', true);
    {% endif %}
    {% if places.row5_place5 == True %}
        $('#id_row5_place5').attr('checked', true);
    {% endif %}
    {% if places.row5_place6 == True %}
        $('#id_row5_place6').attr('checked', true);
    {% endif %}
    {% if places.row5_place7 == True %}
        $('#id_row5_place7').attr('checked', true);
    {% endif %}
    {% if places.row5_place8 == True %}
        $('#id_row5_place8').attr('checked', true);
    {% endif %}
{% endblock %}

movies/templates/main_page.html
{% extends "base.html" %}
{% load thumbnail %}

{% block title %}All movies{% endblock %}

{% block content %}
    <div class="main center fl w-100 pa1">
        {% for movie in movies %}
            <div class="main dib" class="fl w-100 pa1">
                <ul class="db pa0 ma0">
                    <li class='dib films pa3 link b black pv2 db bg-animate hover-bg-light-gray'>
                        <a href="{{ movie.get_absolute_url }}" >
                            {% thumbnail movie.image "300x400" crop='100%' as im %}
                                <img width="300" height="400" src='{{ im.url }}'>
                            {% endthumbnail %}
                            <p class="movie_title link b blue hover-black no-underline">{{ movie.title }}</p>
                        </a>

                    </li>
                </ul>


            </div>
        {% endfor %}
        {% if request.user.is_authenticated %}
            <a href='{% url "add_film" %}'><button  class="f6 link dim ph3 pv2 mb2 center db white bg-mid-gray br3 db center">Add film</button></a>
        {% endif %}
    </div>

{% endblock %}